### ISSUE TITLE
No "exports" main defined in /Users/something/Desktop/something/repos/vue3-playground/node_modules/@nuxt/kit/package.json

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt-community/apollo-module#491]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `devServer`, `modules`, `imports`, `components`, `apollo`, `pinia`, `i18n`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10-27980004.da5534a`, `@nuxtjs/apollo@^5.0.0-alpha.5`, `@pinia/nuxt@^0.4.7`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@^0.4.7`, `@worten/module-logger@1.0.0`, `@worten/module-proxy@1.0.0`
- Build Modules:    `-`

### Describe the bug

Running postinstall script for nuxt 3 is returning the following error:

No "exports" main defined in /Users/something/Desktop/something/repos/vue3-playground/node_modules/@nuxt/kit/package.json

  at new NodeError (node:internal/errors:387:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
  at resolveExports (node:internal/modules/cjs/loader:522:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at _resolve (/Users/something/Desktop/something/repos/vue3-playground/node_modules/jiti/dist/jiti.js:1:241066)
  at jiti (/Users/something/Desktop/something/repos/vue3-playground/node_modules/jiti/dist/jiti.js:1:243188)
  at /Users/something/Desktop/something/repos/vue3-playground/node_modules/@nuxtjs/apollo/dist/module.mjs:4:12

### Expected behaviour

Postinstall script start working while the nuxt apollo module is loaded

**Comment by plcdnl** [comment]
as temporary fix you can edit your package.json with:    
```
...,
"@nuxt/kit": "3.2.3",
"@nuxt/schema": "3.2.3",
...,
```

**Comment by RodrigoProjects** [comment]
@plcdnl Thank you so much, it worked.

Why isn't 'pnpm install' going throw and installing nuxt/kit and nuxt/schema?

**Comment by plcdnl** [comment]
The fact is that nuxt carries with it the latest versions of all packages and they are the ones that are installed, in this way you are only forcing to have old versions of the mentioned packages. I believe there is an update in nuxt/kit which breaks this module. We hope it will be updated soon

**Comment by RodrigoProjects** [comment]
Understood, will check if I can open a issue in nuxt/kit.

**Comment by plcdnl** [comment]
Not sure if the nuxt kit is the problem, maybe it's this module that needs an update

**Comment by Diizzayy** [comment]
@RodrigoProjects @plcdnl This should be fixed in the lastest release (`v5.0.0-alpha.6`)

**Comment by NaCoLiu** [comment]
![image](https://github.com/nuxt-modules/apollo/assets/42311502/b298886d-7f5a-4543-a36d-af193049e7f7)
Recurring bugs @Diizzayy Diizzayy

**Comment by NaCoLiu** [comment]
@Diizzayy

**Comment by raggesilver** [comment]
Still happening in 5.0.0-alpha.6, please reopen.

**Comment by MarcelloTheArcane** [comment]
If I edit remove the following lines from `package.json` it gets past this issue.

https://github.com/nuxt-modules/apollo/blob/0d9f839e655249a3fbb95eba70cb543e53826abe/package.json#L8-L13

That doesn't solve the problem for when I come to run this on the server though...
